name: flutterforge_cli
description: "A Dart CLI that helps Flutter developers get clean structures, apply best practices, and get AI-powered package suggestions."
version: 0.0.5
license: MIT
homepage: https://github.com/Pratyush-who/flutterforge
repository: https://github.com/Pratyush-who/flutterforge
issue_tracker: https://github.com/Pratyush-who/flutterforge/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.5.0
  process_run: ^1.2.4
  args: ^2.7.0
  yaml: ^3.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.26.3

executables:
  flutterforge_cli: flutterforge
  list_models: list_models
  test_generate: test_generate

